### ISSUE TITLE
unavailable

### ISSUE THREAD

**Issue by suurislay** [wlatic/envi_heater#1]
The entity keeps becoming unavailable so i have to  reload the integration then it works normally for  a few minutes then becomes unavailable again.
![Screenshot 2024-04-29 8 20 08 PM](https://github.com/wlatic/envi_heater/assets/157629168/9f52722d-4f67-484d-b10a-aaa30fb2d762)

**Comment by wlatic** [comment]
I believe this may have been because of API auth failing.

0.0.8 should have addressed that, but if you are using that version please let me know.

**Comment by wlatic** [comment]
Have now had 0.0.8 running for just over 12 hours and its still reporting back.

One question I did have is do you have multiple devices or just one? I've not been able to test on multiple heaters yet.

**Comment by suurislay** [comment]
just one thanks the update fixed it

**Comment by wlatic** [comment]
Happy to hear it.

Please let me know of any other issues as it really does help to have a 2nd set of eyes on it.
